### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [waynedgrant/android-appwidget-cirrus#1]
Not complaining, just asking: with no (visible) activity for almost 2 years now, is this project still maintained?

**Comment by waynedgrant** [comment]
Nope :)

**Comment by IzzySoft** [comment]
Aw, well… Thanks for the prompt reply! Maybe you want to state that in the Readme, and then archive the project?

**Comment by waynedgrant** [comment]
This is administrative overhead with little corresponding benefit to me or anyone else. Anyone can look at the commit history to gauge my current level of interest in any of my projects (as you probably did before posing your question). In addition my interest in a project is not a static state of affairs and can wax and wane. I can suddenly pick up a dormant project in response to an idea I've had or a feature request from others. Should I then go to the trouble of removing such a notice only to re-apply it after some subsequent arbitrary period of inactivity occurs? Such process sounds too much like a day job and I already have one of those :)

**Comment by IzzySoft** [comment]
:man_shrugging: So combining your short and your long answer to a medium one:

> Currently not, though I might pick it up again in the future.

Thanks :smile:
